# Generated by Django 6.0.7 on 2026-07-09 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='interests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=255)),
                ('date_beg', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('odd_yes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('odd_no', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_yes', models.IntegerField(default=0)),
                ('total_no', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Closed for voting'), (3, 'Resolved')], default=1)),
                ('outcome', models.IntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No')], null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.category')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OddsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odd_yes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('odd_no', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds_history', to='events.event')),
            ],
        ),
    ]
