# Generated by Django 6.0.7 on 2026-07-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=80, unique=True)),
                ('source', models.CharField(default='Polymarket', max_length=45)),
                ('url', models.URLField(blank=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('suggested_category', models.CharField(blank=True, max_length=45)),
                ('odd_yes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('odd_no', models.DecimalField(decimal_places=2, max_digits=5)),
                ('suggested_deadline', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='external_source_id',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
    ]
