# Generated by Django 6.0.7 on 2026-07-09 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('side', models.IntegerField(choices=[(1, 'Yes'), (2, 'No')])),
                ('odd', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Won'), (3, 'Lost')], default=1)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
